name: linter
on: push
jobs:
  my-job:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        run: npm install
      - name: Run Linter
        run: npm run lint
